package interpenyasrubielos.persistencia.pojos;
// Generated 30-jul-2012 12:52:26 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Pedidos generated by hbm2java
 */
@Entity
@Table(name="pedidos"
    ,catalog="rubielos"
)
public class Pedidos  implements java.io.Serializable {


     private int id;
     private Socios socios;
     private Date fecha;
     private int pagado;
     private int entregado;
     private double importe;

    public Pedidos() {
    }

    public Pedidos(int id, Socios socios, Date fecha, int pagado, int entregado, double importe) {
       this.id = id;
       this.socios = socios;
       this.fecha = fecha;
       this.pagado = pagado;
       this.entregado = entregado;
       this.importe = importe;
    }
   
     @Id 
    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="socio", nullable=false)
    public Socios getSocios() {
        return this.socios;
    }
    
    public void setSocios(Socios socios) {
        this.socios = socios;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="fecha", nullable=false, length=10)
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    
    @Column(name="pagado", nullable=false)
    public int getPagado() {
        return this.pagado;
    }
    
    public void setPagado(int pagado) {
        this.pagado = pagado;
    }
    
    @Column(name="entregado", nullable=false)
    public int getEntregado() {
        return this.entregado;
    }
    
    public void setEntregado(int entregado) {
        this.entregado = entregado;
    }
    
    @Column(name="importe", nullable=false, precision=22, scale=0)
    public double getImporte() {
        return this.importe;
    }
    
    public void setImporte(double importe) {
        this.importe = importe;
    }




}


