package interpenyasrubielos.persistencia.pojos;
// Generated 30-jul-2012 12:52:26 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Penyas generated by hbm2java
 */
@Entity
@Table(name="penyas"
    ,catalog="rubielos"
)
public class Penyas  implements java.io.Serializable {


     private Integer id;
     private String nombre;
     private String telefonos;
     private String direccion;
     private Set<Socios> socioses = new HashSet<Socios>(0);

    public Penyas() {
    }

	
    public Penyas(String nombre, String telefonos, String direccion) {
        this.nombre = nombre;
        this.telefonos = telefonos;
        this.direccion = direccion;
    }
    public Penyas(String nombre, String telefonos, String direccion, Set<Socios> socioses) {
       this.nombre = nombre;
       this.telefonos = telefonos;
       this.direccion = direccion;
       this.socioses = socioses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    
    @Column(name="nombre", nullable=false, length=100)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    
    @Column(name="telefonos", nullable=false)
    public String getTelefonos() {
        return this.telefonos;
    }
    
    public void setTelefonos(String telefonos) {
        this.telefonos = telefonos;
    }
    
    @Column(name="direccion", nullable=false)
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="penyas")
    public Set<Socios> getSocioses() {
        return this.socioses;
    }
    
    public void setSocioses(Set<Socios> socioses) {
        this.socioses = socioses;
    }

    @Override
    public String toString() {
        return this.nombre;
    }

    


}


