package interpenyasrubielos.persistencia.pojos;
// Generated 30-jul-2012 12:52:26 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Ropa generated by hbm2java
 */
@Entity
@Table(name="ropa"
    ,catalog="rubielos"
)
public class Ropa  implements java.io.Serializable {


     private Integer id;
     private String descripcion;
     private String talla;
     private String color;
     private Integer valorColor;
     private Set<RopaSocios> ropaSocioses = new HashSet<RopaSocios>(0);

    public Ropa() {
    }

	
    public Ropa(String descripcion, String talla, String color) {
        this.descripcion = descripcion;
        this.talla = talla;
        this.color = color;
    }
    public Ropa(String descripcion, String talla, String color, Integer valorColor, Set<RopaSocios> ropaSocioses) {
       this.descripcion = descripcion;
       this.talla = talla;
       this.color = color;
       this.valorColor = valorColor;
       this.ropaSocioses = ropaSocioses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    
    @Column(name="descripcion", nullable=false, length=50)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    
    @Column(name="talla", nullable=false, length=50)
    public String getTalla() {
        return this.talla;
    }
    
    public void setTalla(String talla) {
        this.talla = talla;
    }
    
    @Column(name="color", nullable=false, length=50)
    public String getColor() {
        return this.color;
    }
    
    public void setColor(String color) {
        this.color = color;
    }
    
    @Column(name="valorColor")
    public Integer getValorColor() {
        return this.valorColor;
    }
    
    public void setValorColor(Integer valorColor) {
        this.valorColor = valorColor;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="ropa")
    public Set<RopaSocios> getRopaSocioses() {
        return this.ropaSocioses;
    }
    
    public void setRopaSocioses(Set<RopaSocios> ropaSocioses) {
        this.ropaSocioses = ropaSocioses;
    }

    @Override
    public String toString() {
        return this.descripcion+" "+this.talla;
    }
    
    



}


