package interpenyasrubielos.persistencia.pojos;
// Generated 30-jul-2012 12:52:26 by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * RopaSocios generated by hbm2java
 */
@Entity
@Table(name="ropaSocios"
    ,catalog="rubielos"
)
public class RopaSocios  implements java.io.Serializable {


     private Integer id;
     private Ropa ropa;
     private Socios socios;

    public RopaSocios() {
    }

    public RopaSocios(Ropa ropa, Socios socios) {
       this.ropa = ropa;
       this.socios = socios;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="prenda", nullable=false)
    public Ropa getRopa() {
        return this.ropa;
    }
    
    public void setRopa(Ropa ropa) {
        this.ropa = ropa;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="socio", nullable=false)
    public Socios getSocios() {
        return this.socios;
    }
    
    public void setSocios(Socios socios) {
        this.socios = socios;
    }




}


